import { Injectable, NotImplementedException } from "@nestjs/common";
import type { Level } from "@prisma/client";

/**
 * One module-quiz question as generated by AiModule and stored on
 * `module_quizzes.questions`. `answerKey` (recall) and `rubric` (applied)
 * are server-side only — stripped before questions reach the client.
 */
export interface QuizQuestion {
  id: string;
  type: "recall" | "applied";
  prompt: string;
  conceptId: string;
  answerKey?: string;
  rubric?: string;
}

/**
 * Seam for the AiModule generation pipeline (build-order step 5: LangChain.js
 * / LangGraph.js via the Vercel AI Gateway).
 *
 * Until the pipeline lands, cache-miss paths throw a clear error instead of
 * pretending — so endpoint contracts, caching and error handling are all
 * exercised before generation exists.
 */
@Injectable()
export class AiService {
  /**
   * F6 — first-time tutorial generation for a (subtopic, level, styleBucket)
   * cache key. Called synchronously on cache miss (typically a few seconds).
   */
  async generateTutorial(_params: {
    subtopicId: string;
    level: Level;
    styleBucket: string;
  }): Promise<never> {
    throw new NotImplementedException(
      "Tutorial generation not yet implemented — lands with AiModule (build order step 5)",
    );
  }

  /**
   * F7 — module quiz generation. Selects concepts exclusively from the
   * module's existing `subtopic_concepts` mappings; never invents new
   * concept identities. `level` is the course level at generation time.
   */
  async generateModuleQuiz(_params: {
    moduleId: string;
    level: Level;
    concepts: { conceptId: string; canonicalName: string }[];
  }): Promise<QuizQuestion[]> {
    throw new NotImplementedException(
      "Quiz generation not yet implemented — lands with AiModule (build order step 5)",
    );
  }

  /**
   * F7 — LLM grading of an applied (free-text) answer against the
   * question's rubric. Returns the verdict plus a rationale kept on the
   * `quiz_attempts` row for dispute/review.
   */
  async gradeAppliedAnswer(_params: {
    prompt: string;
    rubric: string;
    answer: string;
  }): Promise<{ correct: boolean; rationale: string }> {
    throw new NotImplementedException(
      "Applied-question grading not yet implemented — lands with AiModule (build order step 5)",
    );
  }

  /**
   * F8 — re-angled concept review explanation. Generated once per
   * (conceptId, level, angleVariant) cache key and shared across students.
   * `angleVariant` is server-selected (round-robin over existing variants),
   * not client-specified — same cross-student cache-sharing pattern as F6.
   */
  async regenerateConceptExplanation(_params: {
    conceptId: string;
    canonicalName: string;
    level: Level;
    angleVariant: number;
  }): Promise<string> {
    throw new NotImplementedException(
      "Concept review generation not yet implemented — lands with AiModule (build order step 5)",
    );
  }

  /**
   * F9 — final-project prompt generation once the last module is complete.
   * Ties multiple course concepts to a real, current scenario.
   */
  async generateFinalProjectPrompt(_params: {
    courseId: string;
    courseTitle: string;
    concepts: { conceptId: string; canonicalName: string }[];
  }): Promise<string> {
    throw new NotImplementedException(
      "Final-project generation not yet implemented — lands with AiModule (build order step 5)",
    );
  }

  /**
   * F10 — in-tutorial Q&A answering. Grounded in this subtopic's
   * `tutorial_content`; pulls additional `source_chunks` via vector
   * retrieval when the question needs broader course context.
   */
  async answerQnaQuestion(_params: {
    subtopicId: string;
    question: string;
    tutorialExplanation: string;
  }): Promise<string> {
    throw new NotImplementedException(
      "Q&A answering not yet implemented — lands with AiModule (build order step 5)",
    );
  }

  /**
   * F12 — practice-problem generation for a calc/application-heavy subtopic.
   * Returns an array of problems, each with an ordered hint list and a
   * final solution. Generated once per subtopic and cached.
   */
  async generatePracticeProblems(_params: {
    subtopicId: string;
    subtopicTitle: string;
    level: Level;
    concepts: { conceptId: string; canonicalName: string }[];
  }): Promise<
    { problemText: string; hintsJson: unknown; solution: string }[]
  > {
    throw new NotImplementedException(
      "Practice-problem generation not yet implemented — lands with AiModule (build order step 5)",
    );
  }
}
